### PR TITLE
RR-1003: Overview page changes

### PR DESCRIPTION
**Pull request by lynnette-orr**
Remove padding around 'Add a new goal' in Action card
Slight increase in space above 'Courses and qualifications completed in the last 12 months'

Selected October 11 2024 12:47:09

### CODE REVIEW

**Comment by nathanrussell-moj-digital** [comment]
I'm not sure the styling changes work on the action menu where there are more than 1 item (I hacked the html in chrome dev tools to do this, you might want to try it by adding a new item in the template)
Screenshot 2024-10-11 at 13 57 33

**Comment by nathanrussell-moj-digital** [comment]
Also, I'm not sure your styling change for the courses and quals works in all cases, specifically where there isnt the H3 heading:
Screenshot 2024-10-11 at 14 00 04

Also, I'm not keen on not using the standard govuk class names / styles .... that is what they are there for after all?
Is there not a govuk-heading / govuk-padding type class we can use that gives a 30px space? (the govuk styles are properly responsive as well, so I think we should be using those as preference over and above writing styles like this in the sass)
What do you think?

**Comment by lynnette-orr** [comment]
Removed the custom css. Was able to use padding instead. Modified the Actions card to add some space between multiple items.

Selected October 11 2024 15:10:59

Selected October 11 2024 15:10:16

Selected October 11 2024 15:28:35

Selected October 11 2024 15:29:15

**Review by nathanrussell-moj-digital — APPROVED** [review]
LGTM 👍

**Pull request merged**
